project_id = "meridian-lms"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = false

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[analytics]
enabled = false
